AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ClusterCreateRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "ClusterCreate"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam:: <your-account-id>:root
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess