version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  lint-docker:
    docker:
      - image: cimg/node:16.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Lint Dockerfile for blue and green app
          command: |
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x ./hadolint
            cd blue
            ./hadolint Dockerfile
            cd ..
            cd green
            ./hadolint Dockerfile
            
  build-deploy-app:
    docker:
      - image: circleci/python:3.7.3-stretch
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Setup the virtual environment
          command: |
            echo 'export IMAGE_NAME=capstone_image' >> $BASH_ENV 
            virtualenv capostoneenv
            . capostoneenv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push blue Docker image
          command: |
            . capostoneenv/bin/activate
            cd blue
            docker build -t mjgmora/$IMAGE_NAME:capstone_image_blue .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push mjgmora/$IMAGE_NAME:capstone_image_blue
      - run:
          name: Deploy blue docker image
          command: |
            # Connect to the aws eks cluster and then deploy the replication and service in there??
            cd blue
            ./run_kubernetes.sh
      - run:
          name: Smoke test blue app
          command: |
            echo "Testing blue app deploy was successful"
            # curl the url ?? how to get the url?
      - run:
          name: Build and push green Docker image
          command: |
            . capostoneenv/bin/activate
            cd green
            docker build -t mjgmora/$IMAGE_NAME:capstone_image_green .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push mjgmora/$IMAGE_NAME:capstone_image_green
      - run:
          name: Deploy green docker image
          command: |
            # Connect to the aws eks cluster and then deploy the replication and service in there??
            cd green
            ./run_kubernetes.sh
      - run:
          name: Smoke test green app
          command: |
            echo "Testing green app deploy was successful"
            # curl the url ?? how to get the url?

workflows:
  capstone-workflow:
    jobs:
      - lint-docker
      - build-deploy-app:
          requires: 
            - lint-docker
          