version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  lint-docker:
    docker:
      - image: cimg/node:16.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: |
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x ./hadolint
            ./hadolint Dockerfile
  build-python-app:
    docker:
      - image: circleci/python:3.7.3-stretch
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Setup the virtual environment and build Docker image
          command: |
            virtualenv capostoneenv
            . capostoneenv/bin/activate
            pip install --no-cache-dir -r requirements.txt
            docker build -t mjgmora/capstone_image:0.1.${CIRCLE_BUILD_NUM} .
  deploy-python-app:
    docker:
      - image: circleci/python:3.7.3-stretch
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Push Docker image
          command: |
            . capostoneenv/bin/activate
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push mjgmora/capstone_image:0.1.${CIRCLE_BUILD_NUM}
workflows:
  capstone-workflow:
    jobs:
      - lint-docker
      - build-python-app:
          requires: 
            - lint-docker
      - deploy-python-app:
          requires: 
            - build-python-app
          