version: 2.1

jobs:
  lint-html:
    docker:
      - image: cimg/node:16.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Lint html"
          command: |
            sudo npm i -g html-validate 
            html-validate "index.html" 
  build-docker:
    docker:
      - image: nginx
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo $PATH
      - run: nginx
      - run: nginx -v

workflows:
  prepare-app-workflow:
    jobs:
      - lint-html
      - build-docker:
          requires: [lint-html]