version: 2.1

jobs:
  lint-html:
    docker:
      - image: cimg/node:16.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Lint html"
          command: |
            sudo npm i -g html-validate 
            html-validate "index.html" 
  lint-docker:
    docker:
      - image: cimg/node:16.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Lint Dockerfile"
          command: |
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x ./hadolint
            ./hadolint Dockerfile
  build-nginx:
    docker:
      - image: nginx
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo $PATH
      - run: nginx
      - run: nginx -v
  build-docker-image:
    docker:
      - image: nginx
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Build docker image using script"
          command: |
            sh ./run_docker.sh

workflows:
  prepare-app-workflow:
    jobs:
      - lint-html
      - lint-docker
      - build-nginx:
          requires: [lint-html, lint-docker]
      - build-docker-image:
          requires: [build-nginx]