version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  lint-docker:
    docker:
      - image: cimg/node:16.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: |
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x ./hadolint
            ./hadolint Dockerfile
  build-python-app:
    docker:
      - image: circleci/python:3.7.3-stretch
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Setup the virtual environment
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=capstone_image' >> $BASH_ENV 
            virtualenv capostoneenv
            . capostoneenv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            . capostoneenv/bin/activate
            docker build -t mjgmora/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push mjgmora/$IMAGE_NAME:$TAG
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - run: yum install -y tar gzip
      - run:
          name: Install the eksctl tool
          command: |
            mkdir -p eksctl_download
            curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
              | tar xz -C eksctl_download
            chmod +x eksctl_download/eksctl
            SUDO=""
            if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
              SUDO="sudo"
            fi
            $SUDO mv eksctl_download/eksctl /usr/local/bin/
            rmdir eksctl_download     
            eksctl version >> eksctl_output.txt
            echo "eksctl tools installed corretly with version: "
            cat eksctl_output.txt
      - run:
          name: Install the kubectl tool
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"          
            echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
      - run:
          name: Create eks blue cluster
          command: |
            eksctl create cluster --name my-capstone-blue --region us-east-1
#      - run:
#          name: Create eks green cluster
#          command: |
#            eksctl create cluster --name my-capstone-green --region us-east-1
      - run:
          name: Display nodes and pods installed
          command: |
            kubectl get nodes -o wide
            kubectl get pods -A -o wide
#      - run:
#          name: Create deployment in eks
#          command: |
      - run:
          name: Delete eks clusters
          command: |
            eksctl delete cluster --name my-capstone-blue --region us-east-1
#            eksctl delete cluster --name my-capstone-green --region us-east-1
      - run:
          name: Display nodes and pods deleted
          command: |
            kubectl get nodes -o wide
            kubectl get pods -A -o wide
workflows:
  capstone-workflow:
    jobs:
      - lint-docker
      - build-python-app:
          requires: [lint-docker]
      - deploy-infrastructure:
          requires: [build-python-app]
