apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-capstone-deployment
  namespace: default
  labels:
    app: eks-capstone-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-capstone-app
  template:
    metadata:
      labels:
        app: eks-capstone-app
    spec:
      strategy:
        rollingUpdate:
            maxSurge:25%
            maxUnavailable:25%
        type: RollingUpdate
      containers:
      - name: capstone-project
        image: mjgmora/udacity_clapstone:0.1.193
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Always
      nodeSelector:
        matchLabels: 
            app: eks-capstone-deployment
apiVersion: v1
kind: Service
metadata:
  name: eks-capstone-service
  namespace: default
  labels:
    app: eks-capstone-app
spec:
  type: LoadBalancer
  selector:
    app: eks-capstone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80   
      nodePort: 30000
